# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artbot_website', '0007_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='titleRaw',
            field=models.TextField(),
        ),
    ]
