# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artbot_website', '0009_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='published',
        ),
    ]
