# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-05 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artbot_website', '0010_remove_event_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsoredContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('url_text', models.TextField()),
                ('sponsor', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, b'Draft'), (1, b'Published')], default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
